version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: faculty_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-launcher}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-faculty_launcher}
    ports:
      - "5432:5432"
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U launcher"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    container_name: faculty_minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-admin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./docker-data/minio:/data

  redis:
    image: redis:7-alpine
    container_name: faculty_redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"

  # --- НОВОЕ: Бэкенд ---
  backend:
    build: ./server
    container_name: faculty_backend
    ports:
      - "8000:8000"
    environment:
      # Внутри сети Docker мы обращаемся к сервисам по их именам (postgres, redis, minio)
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-launcher}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB:-faculty_launcher}
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379
      MINIO_URL: minio:9000
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-admin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_USE_SSL: ${MINIO_USE_SSL:-false}
      SECRET_KEY: ${SECRET_KEY}
      ADMIN_IDS: ${ADMIN_IDS}
      DEVELOPER_CHAT_ID: ${DEVELOPER_CHAT_ID}
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
      redis:
        condition: service_started

  # --- Телеграм бот ---
  bot:
    build: ./telegram-bot
    container_name: faculty_bot
    restart: always
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      BACKEND_URL: "http://backend:8000"
      DEVELOPER_CHAT_ID: ${DEVELOPER_CHAT_ID}
    depends_on:
      - backend